# Generated by Django 3.2.7 on 2021-09-17 11:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailuser',
            name='contacts',
            field=models.ManyToManyField(related_name='_users_emailuser_contacts_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
